name: ChatReport
version: '@version@'
authors: [padrewin, 666pyke]
website: 'https://github.com/Cold-Development/ChatReport'
description: A plugin to report players and send their log messages to Discord.
main: dev.padrewin.chatreport.ChatReport
api-version: '1.20'
load: STARTUP
folia-supported: true

commands:
  chatreport:
    aliases: [cr, reportchat]
    description: Root command for ChatReport

permissions:
  chatreport.*:
    description: Gives access to all ChatReport commands
    children:
      chatreport.help: true
      chatreport.reload: true
      chatreport.report: true

  chatreport.help:
    description: Allows access to the help command
    default: true

  chatreport.reload:
    description: Allows access to reload the plugin configuration and locales
    default: op

  chatreport.report:
    description: Allows players to report other players
    default: true
